### ISSUE TITLE
Docker файлы сломали dev окружение

### ISSUE THREAD

**Issue by Vitallium** [IT61/it61-rails#141]
Локально все работает относительно dev базы, даже тесты.
Проблема в файле `config/database.yml` - https://github.com/IT61/it61-rails/blob/master/config/database.yml#L12

Думаю, лучше сделать так:

```
default: &default
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>_development

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>_test

production:
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>

```
